/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#7C3AED',
          dark: '#6D28D9',
          light: '#A855F7',
          hover: '#C084FC',
          muted: '#EDE9FE',
          subtle: '#F5F3FF',
        },
        success: {
          DEFAULT: '#16A34A',
          dark: '#15803D',
          light: '#22C55E',
          muted: '#DCFCE7',
          subtle: '#F0FDF4',
        },
        danger: {
          DEFAULT: '#DC2626',
          dark: '#B91C1C',
          light: '#EF4444',
          muted: '#FEE2E2',
          subtle: '#FEF2F2',
        },
        warning: {
          DEFAULT: '#F59E0B',
          dark: '#D97706',
          light: '#FBBF24',
          muted: '#FEF3C7',
          subtle: '#FFFBEB',
        },
        info: {
          DEFAULT: '#2563EB',
          dark: '#1D4ED8',
          light: '#3B82F6',
          muted: '#DBEAFE',
          subtle: '#EFF6FF',
        },
        accentpurple: {
          DEFAULT: '#A855F7',
          dark: '#7C3AED',
          light: '#C084FC',
          muted: '#EDE9FE',
          subtle: '#F5F3FF',
        },
        surface: '#FFFFFF',
        bg: '#F8FAFC',
        sidebar: '#FFFFFF',
        'sidebar-item': '#F1F5F9',
        'sidebar-active': '#7C3AED',
        border: '#E2E8F0',
        muted: '#94A3B8',
        subtle: '#F1F5F9',
        canvas: { light: '#F8FAFC', dark: '#0B0B0F' },
        panel: { light: '#FFFFFF', dark: '#1B1B26' },
        'panel-secondary': { light: '#F1F5F9', dark: '#15151D' },
        ink: { light: '#0F172A', dark: '#FFFFFF' },
        zinc400: '#B3B3C6',
      },
      fontFamily: {
        sans: ['Inter', 'Plus Jakarta Sans', 'ui-sans-serif', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        mono: ['JetBrains Mono', 'SFMono-Regular', 'Consolas', 'Liberation Mono', 'monospace'],
      },
      boxShadow: {
        card: '0 1px 2px rgb(15 23 42 / 0.03), 0 8px 28px -16px rgb(15 23 42 / 0.16)',
        modal: '0 30px 80px -20px rgb(2 6 23 / 0.35)',
        glow: '0 0 0 1px rgb(124 58 237 / 0.1), 0 14px 40px -16px rgb(124 58 237 / 0.5)',
        premium: '0 1px 2px rgb(15 23 42 / 0.03), 0 14px 40px -22px rgb(15 23 42 / 0.22)',
        'premium-dark': '0 0 0 1px rgb(255 255 255 / 0.025), 0 18px 48px -20px rgb(0 0 0 / 0.75)',
        floating: '0 20px 55px -24px rgb(124 58 237 / 0.45)',
      },
      animation: {
        'fade-in': 'fadeIn 0.35s ease-out both',
        'slide-up': 'slideUp 0.4s cubic-bezier(0.16, 1, 0.3, 1) both',
        'slide-in': 'slideIn 0.35s cubic-bezier(0.16, 1, 0.3, 1) both',
        'scale-in': 'scaleIn 0.28s cubic-bezier(0.16, 1, 0.3, 1) both',
        shimmer: 'shimmer 1.8s linear infinite',
        float: 'float 6s ease-in-out infinite',
        'pulse-soft': 'pulseSoft 2.8s ease-in-out infinite',
        'gradient-x': 'gradientX 7s ease infinite',
        'page-enter': 'pageEnter 0.45s cubic-bezier(0.16, 1, 0.3, 1) both',
      },
      keyframes: {
        fadeIn: { from: { opacity: '0' }, to: { opacity: '1' } },
        slideUp: { from: { opacity: '0', transform: 'translateY(14px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        slideIn: { from: { opacity: '0', transform: 'translateX(-12px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        scaleIn: { from: { opacity: '0', transform: 'scale(0.965)' }, to: { opacity: '1', transform: 'scale(1)' } },
        shimmer: { '0%': { backgroundPosition: '-220% 0' }, '100%': { backgroundPosition: '220% 0' } },
        float: { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-10px)' } },
        pulseSoft: { '0%, 100%': { opacity: '0.55' }, '50%': { opacity: '1' } },
        gradientX: { '0%, 100%': { backgroundPosition: '0% 50%' }, '50%': { backgroundPosition: '100% 50%' } },
        pageEnter: { from: { opacity: '0', transform: 'translateY(8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
      },
      borderRadius: { xl: '12px', '2xl': '16px', '3xl': '20px', '4xl': '26px' },
      transitionTimingFunction: { smooth: 'cubic-bezier(0.16, 1, 0.3, 1)' },
    },
  },
  plugins: [],
};
