// O tutorial usa seletores data-tutorial para não depender de classes visuais.
// `readyElement` indica quando a página terminou de carregar; `element` é o
// alvo que será destacado. TutorialRunner espera os dois ficarem estáveis.
export const TUTORIAL_STEPS = [
  {
    id: 'welcome',
    route: '/dashboard',
    pageReady: '[data-tutorial-page-ready="dashboard"]',
    element: null,
    readyElement: '[data-tutorial="dashboard-summary"]',
    eyebrow: 'Primeiros passos',
    icon: '✦',
    title: 'Bem-vindo ao FinanceHub',
    description: 'Vamos conhecer o fluxo principal do seu controle financeiro. O tour acompanha o carregamento de cada página e você pode encerrá-lo quando quiser.',
    side: 'over',
    align: 'center',
  },
  {
    id: 'month',
    route: '/dashboard',
    pageReady: '[data-tutorial-page-ready="dashboard"]',
    element: '[data-tutorial="month-selector"]',
    readyElement: '[data-tutorial="dashboard-summary"]',
    skipIfHidden: true,
    eyebrow: 'Contexto mensal',
    icon: '◷',
    title: 'Escolha o mês de trabalho',
    description: 'Todas as informações pertencem ao mês selecionado. Use as setas ou o seletor para revisar meses anteriores e planejar os próximos.',
    side: 'bottom',
    align: 'end',
  },
  {
    id: 'summary',
    route: '/dashboard',
    pageReady: '[data-tutorial-page-ready="dashboard"]',
    element: '[data-tutorial="dashboard-summary"]',
    readyElement: '[data-tutorial="dashboard-summary"]',
    eyebrow: 'Visão geral',
    icon: '◎',
    title: 'Seu resumo financeiro',
    description: 'Aqui você acompanha saldo acumulado, receitas, despesas e projeção. Os valores se atualizam conforme os lançamentos são registrados.',
    side: 'bottom',
    align: 'start',
  },
  {
    id: 'health',
    route: '/dashboard',
    pageReady: '[data-tutorial-page-ready="dashboard"]',
    element: '[data-tutorial="financial-health"]',
    readyElement: '[data-tutorial="dashboard-summary"]',
    eyebrow: 'Diagnóstico',
    icon: '♥',
    title: 'Saúde financeira',
    description: 'A pontuação combina renda, despesas, reserva e endividamento. Use o detalhamento para entender quais hábitos estão fortalecendo ou prejudicando seu mês.',
    side: 'top',
    align: 'start',
  },
  {
    id: 'quick-actions',
    route: '/dashboard',
    pageReady: '[data-tutorial-page-ready="dashboard"]',
    element: '[data-tutorial="quick-actions"]',
    readyElement: '[data-tutorial="dashboard-summary"]',
    eyebrow: 'Atalhos',
    icon: '⚡',
    title: 'Ações rápidas',
    description: 'Registre movimentações sem sair do dashboard. No encerramento do mês, o FinanceHub prepara as recorrências e parcelas do próximo período.',
    side: 'top',
    align: 'center',
  },
  {
    id: 'incomes',
    route: '/incomes',
    pageReady: '[data-tutorial-page-ready="incomes"]',
    element: '[data-tutorial="new-income"]',
    readyElement: '[data-tutorial="new-income"]',
    eyebrow: 'Entradas',
    icon: '↗',
    title: 'Cadastre suas receitas',
    description: 'Registre entradas pontuais ou recorrentes. Salários e outras receitas mensais podem ser repetidos automaticamente nos meses seguintes.',
    side: 'left',
    align: 'start',
  },
  {
    id: 'expense-types',
    route: '/expenses',
    pageReady: '[data-tutorial-page-ready="expenses"]',
    element: '[data-tutorial="expense-tabs"]',
    readyElement: '[data-tutorial="expense-tabs"]',
    eyebrow: 'Organização',
    icon: '≡',
    title: 'Separe cada tipo de despesa',
    description: 'Prioridades concentram dívidas e parcelas; Fixas guardam contas recorrentes; Variáveis registram os gastos do cotidiano.',
    side: 'bottom',
    align: 'start',
  },
  {
    id: 'new-expense',
    route: '/expenses',
    pageReady: '[data-tutorial-page-ready="expenses"]',
    element: '[data-tutorial="new-expense-button"]',
    readyElement: '[data-tutorial="expense-tabs"]',
    eyebrow: 'Novo lançamento',
    icon: '−',
    title: 'Registre uma despesa',
    description: 'Ao escolher cartão de crédito, o lançamento entra na fatura correta e consome o limite. O saldo só é reduzido quando a fatura é paga.',
    side: 'left',
    align: 'start',
  },
  {
    id: 'cards',
    route: '/cards',
    pageReady: '[data-tutorial-page-ready="cards"]',
    element: ['[data-tutorial="cards-list"]', '[data-tutorial="cards-empty"]'],
    readyElement: '[data-tutorial="cards-area"]',
    eyebrow: 'Crédito',
    icon: '◇',
    title: 'Cartões e faturas',
    description: 'Acompanhe limite, compras e vencimentos. Mesmo sem cartões cadastrados, esta área mostra o caminho para adicionar o primeiro.',
    side: 'right',
    align: 'start',
  },
  {
    id: 'savings',
    route: '/savings',
    pageReady: '[data-tutorial-page-ready="savings"]',
    element: '[data-tutorial="savings-actions"]',
    readyElement: '[data-tutorial="savings-actions"]',
    eyebrow: 'Proteção',
    icon: '◈',
    title: 'Construa sua reserva',
    description: 'Ao depositar, informe se o dinheiro sai do saldo atual ou se já estava guardado fora do app. Isso mantém o cálculo do caixa fiel à realidade.',
    side: 'bottom',
    align: 'center',
  },
  {
    id: 'goals',
    route: '/goals',
    pageReady: '[data-tutorial-page-ready="goals"]',
    element: '[data-tutorial="new-goal-button"]',
    readyElement: '[data-tutorial="new-goal-button"]',
    eyebrow: 'Objetivos',
    icon: '✦',
    title: 'Transforme planos em metas',
    description: 'Defina valor, prazo e faça aportes. O progresso mostra quanto falta e ajuda a manter seus objetivos visíveis.',
    side: 'left',
    align: 'start',
  },
  {
    id: 'reports',
    route: '/reports',
    pageReady: '[data-tutorial-page-ready="reports"]',
    element: '#report-content',
    readyElement: '#report-content',
    eyebrow: 'Análise',
    icon: '▥',
    title: 'Relatórios completos',
    description: 'Consulte uma visão consolidada e pronta para impressão com resultados, saúde financeira, alertas e recomendações do período.',
    side: 'top',
    align: 'center',
  },
  {
    id: 'settings',
    route: '/settings',
    pageReady: '[data-tutorial-page-ready="settings"]',
    element: '[data-tutorial="tutorial-replay-button"]',
    readyElement: '[data-tutorial="tutorial-replay-button"]',
    eyebrow: 'Personalização',
    icon: '⚙',
    title: 'Configurações e ajuda',
    description: 'Altere perfil, aparência e categorias. Este botão permite rever o tutorial sempre que precisar.',
    side: 'top',
    align: 'center',
  },
];
