// Tutorial estável de uma única rota.
//
// A versão anterior navegava automaticamente entre módulos. Em conexões lentas
// isso podia acumular requisições, deixar o overlay aguardando uma página e
// bloquear a percepção de que o sistema continuava carregando. Agora o tour
// apresenta o dashboard e os demais módulos pela sidebar, sem trocar de rota e
// sem iniciar novas consultas ao backend.
export const TUTORIAL_STEPS = [
  {
    id: 'welcome',
    route: '/dashboard',
    pageReady: '[data-tutorial-page-ready="dashboard"]',
    element: null,
    readyElement: '[data-tutorial="dashboard-summary"]',
    eyebrow: 'Primeiros passos',
    icon: '✦',
    title: 'Bem-vindo ao FinanceHub',
    description: 'Conheça os pontos principais sem sair desta tela. O tutorial não altera dados, não abre outras páginas e pode ser fechado a qualquer momento.',
    side: 'over',
    align: 'center',
  },
  {
    id: 'month',
    route: '/dashboard',
    pageReady: '[data-tutorial-page-ready="dashboard"]',
    element: '[data-tutorial="month-selector"]',
    readyElement: '[data-tutorial="dashboard-summary"]',
    skipIfHidden: true,
    eyebrow: 'Contexto mensal',
    icon: '◷',
    title: 'Escolha o mês de trabalho',
    description: 'Use este controle para revisar meses anteriores ou acompanhar o período atual. Todos os números da tela seguem o mês selecionado.',
    side: 'bottom',
    align: 'end',
  },
  {
    id: 'summary',
    route: '/dashboard',
    pageReady: '[data-tutorial-page-ready="dashboard"]',
    element: '[data-tutorial="dashboard-summary"]',
    readyElement: '[data-tutorial="dashboard-summary"]',
    eyebrow: 'Visão geral',
    icon: '◎',
    title: 'Seu resumo financeiro',
    description: 'Aqui ficam saldo acumulado, receitas, despesas, reserva e projeções. Os valores refletem os lançamentos reais do período.',
    side: 'bottom',
    align: 'start',
  },
  {
    id: 'health',
    route: '/dashboard',
    pageReady: '[data-tutorial-page-ready="dashboard"]',
    element: '[data-tutorial="financial-health"]',
    readyElement: '[data-tutorial="dashboard-summary"]',
    skipIfHidden: true,
    eyebrow: 'Diagnóstico',
    icon: '♥',
    title: 'Saúde financeira',
    description: 'A pontuação combina renda, despesas, reserva e endividamento para mostrar rapidamente onde o mês está saudável ou precisa de atenção.',
    side: 'top',
    align: 'start',
  },
  {
    id: 'quick-actions',
    route: '/dashboard',
    pageReady: '[data-tutorial-page-ready="dashboard"]',
    element: '[data-tutorial="quick-actions"]',
    readyElement: '[data-tutorial="dashboard-summary"]',
    skipIfHidden: true,
    eyebrow: 'Atalhos',
    icon: '⚡',
    title: 'Ações rápidas',
    description: 'Registre receitas, despesas e pagamentos sem abandonar o dashboard. Essas ações usam as mesmas regras financeiras das páginas completas.',
    side: 'top',
    align: 'center',
  },
  {
    id: 'incomes-nav',
    route: '/dashboard',
    pageReady: '[data-tutorial-page-ready="dashboard"]',
    element: '[data-tutorial="nav-incomes"]',
    readyElement: '[data-tutorial="dashboard-summary"]',
    skipIfHidden: true,
    eyebrow: 'Entradas',
    icon: '↗',
    title: 'Receitas',
    description: 'Abra esta área para cadastrar entradas pontuais ou recorrentes, como salário, comissão e renda extra.',
    side: 'right',
    align: 'center',
  },
  {
    id: 'expenses-nav',
    route: '/dashboard',
    pageReady: '[data-tutorial-page-ready="dashboard"]',
    element: '[data-tutorial="nav-expenses"]',
    readyElement: '[data-tutorial="dashboard-summary"]',
    skipIfHidden: true,
    eyebrow: 'Saídas',
    icon: '−',
    title: 'Despesas e dívidas',
    description: 'Aqui você organiza prioridades, despesas fixas e gastos variáveis, incluindo cobranças lançadas corretamente no cartão.',
    side: 'right',
    align: 'center',
  },
  {
    id: 'cards-nav',
    route: '/dashboard',
    pageReady: '[data-tutorial-page-ready="dashboard"]',
    element: '[data-tutorial="nav-cards"]',
    readyElement: '[data-tutorial="dashboard-summary"]',
    skipIfHidden: true,
    eyebrow: 'Crédito',
    icon: '◇',
    title: 'Cartões e faturas',
    description: 'Acompanhe limite disponível, compras, fechamento, vencimento e pagamento das faturas em um único lugar.',
    side: 'right',
    align: 'center',
  },
  {
    id: 'planning-nav',
    route: '/dashboard',
    pageReady: '[data-tutorial-page-ready="dashboard"]',
    element: ['[data-tutorial="nav-savings"]', '[data-tutorial="nav-goals"]'],
    readyElement: '[data-tutorial="dashboard-summary"]',
    skipIfHidden: true,
    eyebrow: 'Planejamento',
    icon: '◈',
    title: 'Reserva e metas',
    description: 'Use estes módulos para separar sua reserva financeira e acompanhar objetivos sem confundir dinheiro guardado com saldo disponível.',
    side: 'right',
    align: 'center',
  },
  {
    id: 'intelligence-nav',
    route: '/dashboard',
    pageReady: '[data-tutorial-page-ready="dashboard"]',
    element: ['[data-tutorial="nav-reports"]', '[data-tutorial="nav-trends"]'],
    readyElement: '[data-tutorial="dashboard-summary"]',
    skipIfHidden: true,
    eyebrow: 'Inteligência',
    icon: '▥',
    title: 'Análises e relatórios',
    description: 'Relatórios, tendências, histórico e simuladores ajudam a entender padrões e avaliar decisões antes de comprometer o orçamento.',
    side: 'right',
    align: 'center',
  },
  {
    id: 'settings-nav',
    route: '/dashboard',
    pageReady: '[data-tutorial-page-ready="dashboard"]',
    element: '[data-tutorial="nav-settings"]',
    readyElement: '[data-tutorial="dashboard-summary"]',
    skipIfHidden: true,
    eyebrow: 'Personalização',
    icon: '⚙',
    title: 'Configurações e ajuda',
    description: 'Altere perfil, aparência e categorias. Dentro desta página você também pode iniciar o tutorial novamente quando precisar.',
    side: 'right',
    align: 'center',
  },
];
