// Tutorial estável de uma única rota.
//
// A versão anterior navegava automaticamente entre módulos. Em conexões lentas
// isso podia acumular requisições, deixar o overlay aguardando uma página e
// bloquear a percepção de que o sistema continuava carregando. Agora o tour
// apresenta o dashboard e os demais módulos pela sidebar, sem trocar de rota e
// sem iniciar novas consultas ao backend.
export const TUTORIAL_STEPS = [
  {
    id: 'welcome',
    route: '/dashboard',
    pageReady: '[data-tutorial-page-ready="dashboard"]',
    element: null,
    readyElement: '[data-tutorial="dashboard-summary"]',
    eyebrow: 'Primeiros passos',
    icon: '✦',
    title: 'Bem-vindo ao FinanceHub',
    description: 'Conheça os pontos principais sem sair desta tela. O tutorial não altera dados, não abre outras páginas e pode ser fechado a qualquer momento.',
    side: 'over',
    align: 'center',
  },
  {
    id: 'month',
    route: '/dashboard',
    pageReady: '[data-tutorial-page-ready="dashboard"]',
    element: '[data-tutorial="month-selector"]',
    readyElement: '[data-tutorial="dashboard-summary"]',
    skipIfHidden: true,
    eyebrow: 'Contexto mensal',
    icon: '◷',
    title: 'Escolha o mês de trabalho',
    description: 'Use este controle para revisar meses anteriores ou acompanhar o período atual. Todos os lançamentos usam o mês selecionado, e não a data do seu computador. Meses encerrados ficam somente para leitura — para registrar algo novo, selecione um mês aberto.',
    side: 'bottom',
    align: 'end',
  },
  {
    id: 'summary',
    route: '/dashboard',
    pageReady: '[data-tutorial-page-ready="dashboard"]',
    element: '[data-tutorial="dashboard-summary"]',
    readyElement: '[data-tutorial="dashboard-summary"]',
    eyebrow: 'Visão geral',
    icon: '◎',
    title: 'Seu resumo financeiro',
    description: 'Aqui ficam o saldo disponível, o patrimônio financeiro (saldo + dinheiro físico + reservas + metas), as dívidas e as projeções. Guardar dinheiro move o valor entre esses componentes sem alterar seu patrimônio total.',
    side: 'bottom',
    align: 'start',
  },
  {
    id: 'health',
    route: '/dashboard',
    pageReady: '[data-tutorial-page-ready="dashboard"]',
    element: '[data-tutorial="financial-health"]',
    readyElement: '[data-tutorial="dashboard-summary"]',
    skipIfHidden: true,
    eyebrow: 'Diagnóstico',
    icon: '♥',
    title: 'Saúde financeira',
    description: 'A pontuação combina renda, despesas, reserva e endividamento para mostrar rapidamente onde o mês está saudável ou precisa de atenção.',
    side: 'top',
    align: 'start',
  },
  {
    id: 'quick-actions',
    route: '/dashboard',
    pageReady: '[data-tutorial-page-ready="dashboard"]',
    element: '[data-tutorial="quick-actions"]',
    readyElement: '[data-tutorial="dashboard-summary"]',
    skipIfHidden: true,
    eyebrow: 'Atalhos',
    icon: '⚡',
    title: 'Ações rápidas',
    description: 'Registre receitas, despesas e pagamentos sem abandonar o dashboard. Essas ações usam as mesmas regras financeiras das páginas completas.',
    side: 'top',
    align: 'center',
  },
  {
    id: 'incomes-nav',
    route: '/dashboard',
    pageReady: '[data-tutorial-page-ready="dashboard"]',
    element: '[data-tutorial="nav-incomes"]',
    readyElement: '[data-tutorial="dashboard-summary"]',
    skipIfHidden: true,
    eyebrow: 'Entradas',
    icon: '↗',
    title: 'Receitas',
    description: 'Cadastre salários e outras entradas. O valor entra no saldo disponível na hora — a data serve para organizar a competência e os relatórios, não para adiar o dinheiro. Receitas recorrentes são recriadas sozinhas a cada fechamento de mês.',
    side: 'right',
    align: 'center',
  },
  {
    id: 'expenses-nav',
    route: '/dashboard',
    pageReady: '[data-tutorial-page-ready="dashboard"]',
    element: '[data-tutorial="nav-expenses"]',
    readyElement: '[data-tutorial="dashboard-summary"]',
    skipIfHidden: true,
    eyebrow: 'Saídas',
    icon: '−',
    title: 'Despesas e dívidas',
    description: 'Registre despesas e dívidas. O pagamento usa apenas três formas com efeitos distintos: saldo da conta, dinheiro físico ou cartão de crédito. Despesa pendente não desconta o saldo; só o pagamento desconta. Dívidas continuam ativas até o saldo devedor chegar a zero, mesmo com pagamentos flexíveis.',
    side: 'right',
    align: 'center',
  },
  {
    id: 'cards-nav',
    route: '/dashboard',
    pageReady: '[data-tutorial-page-ready="dashboard"]',
    element: '[data-tutorial="nav-cards"]',
    readyElement: '[data-tutorial="dashboard-summary"]',
    skipIfHidden: true,
    eyebrow: 'Crédito',
    icon: '◇',
    title: 'Cartões e faturas',
    description: 'A compra no cartão não sai do saldo na hora: entra na fatura e o saldo só cai quando você paga a fatura. Compras até o dia do fechamento entram na fatura atual; depois disso, na próxima. Uma despesa fixa no cartão aparece em Despesas Fixas e também na fatura, mas conta uma única vez no seu total.',
    side: 'right',
    align: 'center',
  },
  {
    id: 'planning-nav',
    route: '/dashboard',
    pageReady: '[data-tutorial-page-ready="dashboard"]',
    element: ['[data-tutorial="nav-savings"]', '[data-tutorial="nav-goals"]'],
    readyElement: '[data-tutorial="dashboard-summary"]',
    skipIfHidden: true,
    eyebrow: 'Planejamento',
    icon: '◈',
    title: 'Reserva e metas',
    description: 'Guarde dinheiro em caixinhas e metas. Depositar do saldo reduz o saldo disponível; retirar devolve. Transferir entre caixinhas não altera saldo nem patrimônio. Se você registra dinheiro que já tinha guardado fora do app (origem externa), a reserva aumenta sem tirar do seu saldo.',
    side: 'right',
    align: 'center',
  },
  {
    id: 'intelligence-nav',
    route: '/dashboard',
    pageReady: '[data-tutorial-page-ready="dashboard"]',
    element: ['[data-tutorial="nav-reports"]', '[data-tutorial="nav-trends"]'],
    readyElement: '[data-tutorial="dashboard-summary"]',
    skipIfHidden: true,
    eyebrow: 'Inteligência',
    icon: '▥',
    title: 'Análises e relatórios',
    description: 'Relatórios, tendências, histórico e simuladores ajudam a entender padrões e avaliar decisões antes de comprometer o orçamento.',
    side: 'right',
    align: 'center',
  },
  {
    id: 'settings-nav',
    route: '/dashboard',
    pageReady: '[data-tutorial-page-ready="dashboard"]',
    element: '[data-tutorial="nav-settings"]',
    readyElement: '[data-tutorial="dashboard-summary"]',
    skipIfHidden: true,
    eyebrow: 'Personalização',
    icon: '⚙',
    title: 'Configurações e ajuda',
    description: 'Altere perfil, aparência e categorias. Dentro desta página você também pode iniciar o tutorial novamente quando precisar.',
    side: 'right',
    align: 'center',
  },
];
